import Link from 'next/link'
import type { Metadata } from 'next'
import { SprintBuildWordmark } from '@/components/marketing/logo'
import { Footer } from '@/components/marketing/footer'
import { CONTACT_EMAILS } from '@/lib/site'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    'How SprintBuild collects, uses, and protects your data, including details on cookies and third-party processors.',
}

const LAST_UPDATED = 'May 18, 2026'

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#f0f0ee] flex flex-col">
      <header className="px-6 sm:px-12 md:px-20 lg:px-28 pt-6 flex items-center justify-between">
        <Link href="/" aria-label="SprintBuild home">
          <SprintBuildWordmark size="md" />
        </Link>
        <nav className="hidden sm:flex items-center gap-6 text-[12px] text-gray-500">
          <Link href="/" className="hover:text-gray-900 transition-colors">
            Home
          </Link>
          <Link href="/blog" className="hover:text-gray-900 transition-colors">
            Blog
          </Link>
          <Link
            href="/login"
            className="hover:text-gray-900 transition-colors"
          >
            Sign in
          </Link>
        </nav>
      </header>

      <section className="px-6 sm:px-12 md:px-20 lg:px-28 py-14 sm:py-20">
        <div className="max-w-3xl mx-auto">
          <p className="text-[12px] uppercase tracking-[0.18em] text-blue-500 font-medium mb-3">
            Legal
          </p>
          <h1 className="text-3xl sm:text-4xl font-medium tracking-tight text-gray-900 mb-3">
            Privacy Policy
          </h1>
          <p className="text-[12px] text-gray-400 font-mono">
            Last updated: {LAST_UPDATED}
          </p>
        </div>
      </section>

      <section className="flex-1 px-6 sm:px-12 md:px-20 lg:px-28 pb-20">
        <article className="max-w-3xl mx-auto space-y-10 text-[14px] leading-relaxed text-gray-700">
          <p>
            This Privacy Policy explains how SprintBuild
            (&ldquo;SprintBuild&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;)
            collects, uses, and shares information when you use our website,
            dashboard, AI agent, and related services (the
            &ldquo;Service&rdquo;). By using the Service you agree to the
            practices described here.
          </p>

          <section className="space-y-3">
            <h2 className="text-[18px] font-medium tracking-tight text-gray-900">
              1. Information we collect
            </h2>
            <p>We collect three categories of information:</p>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>
                <span className="font-medium text-gray-900">
                  Account information.
                </span>{' '}
                Email address, password hash, and (optionally) GitHub profile
                data when you sign in with GitHub.
              </li>
              <li>
                <span className="font-medium text-gray-900">
                  Usage and content.
                </span>{' '}
                Prompts you submit, files generated by the AI agent, command
                logs, sandbox metadata, and project history.
              </li>
              <li>
                <span className="font-medium text-gray-900">
                  Technical data.
                </span>{' '}
                IP address, user agent, device type, referrer, approximate
                location, and product analytics events such as page views and
                feature usage.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-[18px] font-medium tracking-tight text-gray-900">
              2. How we use information
            </h2>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>To operate, maintain, and secure the Service.</li>
              <li>
                To authenticate you, route requests, and run sandboxed code on
                your behalf.
              </li>
              <li>
                To improve product quality, debug issues, and prioritize new
                features.
              </li>
              <li>
                To communicate with you about your account, security, and
                product updates.
              </li>
              <li>
                To enforce our{' '}
                <Link
                  href="/terms"
                  className="text-blue-500 hover:text-blue-600 transition-colors"
                >
                  Terms and Conditions
                </Link>{' '}
                and comply with legal obligations.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-[18px] font-medium tracking-tight text-gray-900">
              3. Cookies and similar technologies
            </h2>
            <p>
              SprintBuild uses cookies and similar technologies for the
              following purposes:
            </p>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>
                <span className="font-medium text-gray-900">
                  Strictly necessary.
                </span>{' '}
                Authentication, session, security, and load balancing. These
                cookies are required for the Service to function and cannot be
                turned off in our systems.
              </li>
              <li>
                <span className="font-medium text-gray-900">Preferences.</span>{' '}
                Theme, language, and UI choices so the product remembers how
                you like it.
              </li>
              <li>
                <span className="font-medium text-gray-900">Analytics.</span>{' '}
                Aggregate usage data to understand which features are useful.
                Loaded only after you give consent via the cookie banner.
              </li>
            </ul>
            <p>
              You can manage non-essential cookies via the consent banner shown
              on first visit. You can revisit your choice at any time by
              clearing the <code className="font-mono text-[12px]">sb_cookie_consent</code>{' '}
              cookie from your browser. Disabling strictly necessary cookies
              will break parts of the Service such as sign-in.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-[18px] font-medium tracking-tight text-gray-900">
              4. Third-party processors
            </h2>
            <p>
              We use carefully selected vendors to operate the Service. They
              process data on our behalf under contractual safeguards:
            </p>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>
                <span className="font-medium text-gray-900">Vercel</span> &mdash;
                hosting, AI Gateway, and sandboxed code execution.
              </li>
              <li>
                <span className="font-medium text-gray-900">Supabase</span>{' '}
                &mdash; authentication, Postgres database, and file storage.
              </li>
              <li>
                <span className="font-medium text-gray-900">GitHub</span>{' '}
                &mdash; OAuth sign-in (only if you choose that option).
              </li>
              <li>
                <span className="font-medium text-gray-900">
                  Anthropic, OpenAI, xAI
                </span>{' '}
                &mdash; large language model inference for AI features.
                Prompts and generated outputs are sent to whichever provider
                you select.
              </li>
            </ul>
            <p>
              Each provider is bound by their own privacy policy and data
              processing terms. We do not sell your personal information.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-[18px] font-medium tracking-tight text-gray-900">
              5. Data retention
            </h2>
            <p>
              We retain account information for as long as your account is
              active. Project files, prompts, and logs are retained until you
              delete them or close your account. Aggregated, de-identified
              analytics may be retained longer. Backup copies are purged on a
              rolling 30-day cycle.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-[18px] font-medium tracking-tight text-gray-900">
              6. Your rights
            </h2>
            <p>
              Depending on where you live (e.g., EEA, UK, California, Brazil),
              you may have rights to access, correct, export, or delete your
              personal information, to object to or restrict certain
              processing, and to withdraw consent. Email{' '}
              <a
                href={`mailto:${CONTACT_EMAILS.privacy}`}
                className="text-blue-500 hover:text-blue-600 transition-colors"
              >
                {CONTACT_EMAILS.privacy}
              </a>{' '}
              to exercise any of these rights. We will respond within the
              timeframe required by applicable law.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-[18px] font-medium tracking-tight text-gray-900">
              7. International transfers
            </h2>
            <p>
              SprintBuild is operated from the United States and our processors
              may store and process data in other countries. Where required, we
              rely on Standard Contractual Clauses or equivalent safeguards
              when transferring personal information across borders.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-[18px] font-medium tracking-tight text-gray-900">
              8. Security
            </h2>
            <p>
              We use industry-standard safeguards including TLS in transit,
              encryption at rest for sensitive fields, sandbox isolation for
              executed code, and least-privilege access controls. No system is
              perfectly secure; if you believe your account has been
              compromised, contact us immediately.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-[18px] font-medium tracking-tight text-gray-900">
              9. Children
            </h2>
            <p>
              The Service is not intended for children under 13. We do not
              knowingly collect personal information from children under 13. If
              you believe a child has provided us with personal information,
              email{' '}
              <a
                href={`mailto:${CONTACT_EMAILS.privacy}`}
                className="text-blue-500 hover:text-blue-600 transition-colors"
              >
                {CONTACT_EMAILS.privacy}
              </a>{' '}
              and we will delete it.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-[18px] font-medium tracking-tight text-gray-900">
              10. Changes to this policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. If we make
              material changes, we will notify you in-product or by email at
              least 7 days before the change takes effect. The &ldquo;Last
              updated&rdquo; date at the top reflects the current version.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-[18px] font-medium tracking-tight text-gray-900">
              11. Contact
            </h2>
            <p>
              Questions or privacy requests? Email{' '}
              <a
                href={`mailto:${CONTACT_EMAILS.privacy}`}
                className="text-blue-500 hover:text-blue-600 transition-colors"
              >
                {CONTACT_EMAILS.privacy}
              </a>
              .
            </p>
          </section>

          <p className="text-[12px] text-gray-400">
            See also our{' '}
            <Link
              href="/terms"
              className="text-blue-500 hover:text-blue-600 transition-colors"
            >
              Terms and Conditions
            </Link>
            .
          </p>
        </article>
      </section>

      <Footer />
    </main>
  )
}
